baseURL = 'https://aakashkh.github.io/data-patterns/'
languageCode = 'en-us'
title = 'Data Patterns'

[markup.goldmark.renderer]
  unsafe = true  # Enable raw HTML in markdown

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.typographer]
        disable = false
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"

[permalinks]
  blog = "/:section/:year/:month/:day/:slug/"
  posts = "/blog/:year/:month/:day/:slug/"
  categories = "/categories/:slug/"
  tags = "/tags/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = true
  style = "monokai"

[params]
  github_repo = "https://github.com/aakashkh/data-patterns"
  github_branch = "main"
