baseURL = 'https://aakashkh.github.io/data-patterns'
languageCode = 'en-us'
title = 'Data Patterns'

[markup]
  # Table of Contents Configuration
  [markup.tableOfContents]
    startLevel = 2  # Start with h2 headings
    endLevel = 4    # Include up to h4 headings
    ordered = false  # Use unordered lists for TOC
    
  # Goldmark Configuration
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      [markup.goldmark.extensions.typographer]
        disable = false
        
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      
    [markup.goldmark.renderer]
      unsafe = true  # Allow raw HTML in markdown
      
  # Syntax Highlighting Configuration
  [markup.highlight]
    # Enable code fences and syntax guessing
    codeFences = true
    guessSyntax = true
    
    # Disable line numbers (we'll handle them with CSS if needed)
    lineNos = false
    
    # Disable default classes to prevent extra wrapper divs
    noClasses = true
    
    # Use monokai theme for syntax highlighting
    style = "monokai"
    
    # Set tab width for code blocks
    tabWidth = 4
    
    # Additional options
    lineNumbersInTable = false
    noHl = false

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"
  categories = "/categories/:slug/"
  tags = "/tags/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[params]
  github_repo = "https://github.com/aakashkh/data-patterns"
  github_branch = "main"
