baseURL = 'https://aakashkh.github.io/data-patterns'
languageCode = 'en-us'
title = 'Data Patterns'

[markup.goldmark.renderer]
  unsafe = true  # Enable raw HTML in markdown

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.typographer]
        disable = false
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"
  categories = "/categories/:slug/"
  tags = "/tags/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[markup.highlight]
  # Enable code fences and syntax guessing
  codeFences = true
  guessSyntax = true
  
  # Disable line numbers (we'll handle them with CSS if needed)
  lineNos = false
  
  # Disable default classes to prevent extra wrapper divs
  noClasses = true
  
  # Use monokai theme for syntax highlighting
  style = "monokai"
  
  # Set tab width for code blocks
  tabWidth = 4
  
  # Additional options
  lineNumbersInTable = false
  noHl = false

[params]
  github_repo = "https://github.com/aakashkh/data-patterns"
  github_branch = "main"
